<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <!-- Zielverzeichnisse je nach Konfiguration -->
  <PropertyGroup Condition="'$(Configuration)'=='Release-DE'">
    <TargetCopyDir>$(SolutionDir)..\COMPILED_DE\</TargetCopyDir>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release-EN'">
    <TargetCopyDir>$(SolutionDir)..\COMPILED_EN\</TargetCopyDir>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release-FR'">
    <TargetCopyDir>$(SolutionDir)..\COMPILED_FR\</TargetCopyDir>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <TargetCopyDir>$(SolutionDir)..\COMPILED\</TargetCopyDir>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <TargetCopyDir>$(SolutionDir)..\COMPILED_DEBUG\</TargetCopyDir>
  </PropertyGroup>

<!-- Kopiert fertiges Artefakt ins Zielverzeichnis -->
  <Target Name="PostBuildCopy" AfterTargets="Build" Condition=" '$(TargetCopyDir)' != '' ">
    <MakeDir Directories="$(TargetCopyDir)" />
    <Copy SourceFiles="$(TargetPath)"
          DestinationFolder="$(TargetCopyDir)"
          SkipUnchangedFiles="true" />
    <!-- PDB nur mitkopieren, wenn eine existiert (also im Debug-Build) -->
    <Copy SourceFiles="$(TargetDir)$(TargetName).pdb"
          DestinationFolder="$(TargetCopyDir)"
          SkipUnchangedFiles="true"
          Condition="Exists('$(TargetDir)$(TargetName).pdb')" />
  </Target>

</Project>
